#!/usr/bin/env bash

name="vpn"
params="-v $(pwd)/volume:/etc/openvpn --cap-add=NET_ADMIN kylemanna/openvpn"

if [ $# -gt 0 ]; then

  if [ "$1" == "init" ]; then
    shift 1
    mkdir -p clients
    docker run --rm -it $params ovpn_genconfig -u udp://$@
    docker run --rm -it $params ovpn_initpki

  elif [ "$1" == "start" ]; then
    docker run -d --restart always --name $name -p 1194:1194/udp $params

  elif [ "$1" == "stop" ]; then
    docker stop $name && docker rm $name

  elif [ "$1" == "add" ]; then
    shift 1
    docker run --rm -it $params easyrsa build-client-full $@ nopass
    docker run --rm -it $params ovpn_getclient $@ > clients/$@.ovpn

  elif [ "$1" == "remove" ]; then
    shift 1
    docker run --rm -it $params ovpn_revokeclient $@ remove && rm clients/$@.ovpn
  fi

else
  docker ps --filter "name=$name"
fi
